### ISSUE TITLE
Python inference script not running

### ISSUE THREAD

**Issue by sehgal15** [Alxaline/BraTS21#1]
Hi @Alxaline, 

Thank you for sharing your work. 
I am trying to run the inference command after downloading the weights and get the following error:

`EquiUnetASSP features: [48, 96, 192, 384]
EquiUnetASSP features: [48, 96, 192, 384]
EquiUnetASSP features: [48, 96, 192, 384]
EquiUnetASSP features: [48, 96, 192, 384]
EquiUnetASSP features: [48, 96, 192, 384]
EquiUnetASSP features: [48, 96, 192, 384]
EquiUnetASSP features: [48, 96, 192, 384]
EquiUnetASSP features: [48, 96, 192, 384]
EquiUnetASSP features: [48, 96, 192, 384]
EquiUnetASSP features: [48, 96, 192, 384]
Traceback (most recent call last):
  File "/home/miniconda3/envs/BraTS21/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/envs/BraTS21/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/BraTS21/src/main_inference.py", line 96, in <module>
    main()
  File "/home/BraTS21/src/main_inference.py", line 92, in main
    True)
  File "/home/BraTS21/learning/engine.py", line 197, in evaluate
    self._set_meters(args, len(data_loader), f"Epoch Valid: [{epoch}]", step_mode=step_mode)
TypeError: object of type 'NoneType' has no len()`

Input folder has following files:

BraTS2021_00621_flair.nii.gz  BraTS2021_00621_seg.nii.gz  BraTS2021_00621_t1.nii.gz  BraTS2021_00621_t1ce.nii.gz  BraTS2021_00621_t2.nii.gz

Can you please help?

**Comment by sehgal15** [comment]
Fixed: Input folder directory was incorrectly passed. Input directory should be one level up from the Brats folders
